[profile.default]
src = "src"
out = "out"
libs = ["lib"]


[fuzz]
runs = 500   # default is 256

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
